[workspace]
members = ["machine"]

[package]
authors = ["Linus Oleander <linus@oleander.io>"]
version = "0.1.0"
edition = "2021"
name = "u701"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"
name = "u701"

[dependencies]
lazy_static = { version = "1.4.0", default-features = false }
env_logger = { version = "0.10.1", default-features = false }
anyhow = { version = "1.0.75", default-features = false }
log = { version = "0.4.20", default-features = false }
crossbeam-channel = "0.5.8"
libc = "0.2.150"

machine = { path = "machine" }

[dependencies.tokio]
features = ["rt-multi-thread", "macros", "time", "sync"]
default-features = false
version = "1.35.0"

[dependencies.thingbuf]
default-features = false
features = ["static"]
version = "0.1.4"

[profile.dev]
codegen-units = 1
opt-level = "z"

[profile.release]
codegen-units = 1
opt-level = 3
debug = true
lto = true

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3
