[package]
authors = ["Linus Oleander <linus@oleander.io>"]
version = "0.1.0"
edition = "2021"
name = "u701"

[dependencies]
lazy_static = { version = "1.4.0", default-features = false }
thingbuf = { version = "0.1.4", default-features = true }
anyhow = { version = "1.0.75", default-features = false }

[lib]
crate-type = ["staticlib", "lib"]
path = "src/lib.rs"
name = "u701"
