[package]
version = "0.1.0"
edition = "2021"
build = "build.rs"
name = "u701"

[dependencies]
spin = { version = "0.9.8", default-features = false, features = ["mutex", "spin_mutex"] }
lazy_static = { version = "1.4.0", default-features = false, features = ["spin_no_std"] }
esp32-nimble = { git = "https://github.com/taks/esp32-nimble.git", branch = "develop" }
esp-idf-sys = { version = "0.33.7", features = ["native", "binstart"] }
anyhow = { version = "1.0.75", default-features = false }
log = { version = "0.4.20", default-features = false }
linked_list_allocator = "0.10.5"
esp-idf-hal = "0.42.5"
esp-idf-svc = "0.47.3"
hashbrown = "0.11.2"
libc = "0.2.150"

[build-dependencies]
clang-sys = "1.6.1"
embuild = "0.31.4"
bindgen = "0.69.1"
glob = "0.3.1"

[package.metadata.esp-idf-sys]
freertos_hz = 1000
esp_idf_sdkconfig_defaults = ["sdkconfig.defaults", "sdkconfig.defaults.ble"]


[lib]
crate-type = ["staticlib", "lib"]
path = "src/lib.rs"
name = "u701"
