[package]
version = "0.1.0"
edition = "2021"
name = "u701"

[dependencies]
spin = { version = "0.9.8", default-features = false, features = ["mutex", "spin_mutex"] }
lazy_static = { version = "1.4.0", default-features = false, features = ["spin_no_std"] }
hashbrown = { version = "0.11.2", default-features = true }
anyhow = { version = "1.0.75", default-features = false }
log = { version = "0.4.20", default-features = false }
linked_list_allocator = "0.10.5"

[lib]
crate-type = ["staticlib", "lib"]
path = "src/lib.rs"
name = "u701"
