[workspace]
members = ["machine"]

[package]
authors = ["Linus Oleander <linus@oleander.io>"]
version = "0.1.0"
edition = "2021"
name = "u701"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"
name = "u701"

[dependencies]
lazy_static = { version = "1.4.0", default-features = false }
env_logger = { version = "0.10.1", default-features = false }
anyhow = { version = "1.0.75", default-features = false }
log = { version = "0.4.20", default-features = false }
libc = { version = "0.2.151", default-features = false }

machine = { path = "machine" }

[dependencies.tokio]
features = ["rt", "macros", "time", "sync"]
default-features = false
version = "1.35.0"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"

[profile.release.package."*"]
codegen-units = 1
opt-level = 3

[profile.dev]
debug = true
opt-level = "z"
