[package]
version = "0.1.0"
edition = "2021"
name = "u701"

[dependencies]
anyhow = { version = "1.0.75", default-features = false }
hashbrown = { version = "0.11.2", default-features = false }
lazy_static = { version = "1.4.0", default-features = false, features = ["spin_no_std"] }
# thingbuf = { version = "0.1.4", default-features = false, features = ["static"] }
# lazy_static = { version = "1.4.0", default-features = false }
# env_logger = { version = "0.1 0.0", default-features = false }
# anyhow = { version = "1.0.75", default-features = false }
log = { version = "0.4.20", default-features = false }
spin = { version = "0.9.8", default-features = false, features = ["mutex", "spin_mutex"] }

[lib]
crate-type = ["staticlib", "lib"]
path = "src/lib.rs"
name = "u701"
