[package]
authors = ["Linus Oleander <linus.oleander@clark.de>"]
version = "0.1.0"
edition = "2021"
name = "u701"

[dependencies]
esp-idf-sys = "0.33.2"
esp-idf-svc = "0.46.2"
esp-idf-hal = "0.41.2"
lazy_static = "1.4.0"
hashbrown = "0.14.1"
libc = "0.2.149"
log = "0.4.20"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"
name = "u701"

[package.metadata.esp-idf-sys]
esp_idf_version = "release/v4.4"

[build-dependencies]
embuild = "0.31.2"
