[package]
authors = ["Linus Oleander <linus@oleander.io>"]
version = "0.1.0"
edition = "2021"
name = "u701"

[dependencies]
lazy_static = { version = "1.4.0", default-features = false }
thingbuf = "0.1.4"
anyhow = "1.0.75"
mockall = "0.11.4"

[lib]
crate-type = ["staticlib", "lib"]
path = "src/lib.rs"
name = "u701"
