[package]
authors = ["Linus Oleander <linus@oleander.io>"]
version = "0.1.0"
edition = "2021"
name = "u701"

[dependencies]
esp-idf-svc = { version = "0.47.1", default-features = false, features = ["std"] }
hashbrown = { version = "0.14.1", default-features = false, features = ["ahash"] }
esp-idf-sys = { version = "0.33.2", default-features = false }
esp-idf-hal = { version = "0.42.1", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
# libc = { version = "0.2.149", default-features = false }
log = { version = "0.4.20", default-features = false }

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"
name = "u701"

[package.metadata.esp-idf-sys]
esp_idf_version = "release/v4.4"

[build-dependencies]
embuild = "0.31.2"
