[package]
authors = ["Linus Oleander <linus.oleander@clark.de>"]
version = "0.1.0"
edition = "2021"
name = "u701hybrid"

[dependencies]
# tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros", "time"] }
# esp-idf-sys = "0.33.2"
# esp-idf-svc = "0.46.2"
log = "0.4.20"
# esp-idf-hal = "0.41.2"
# esp32-nimble = "0.2.1"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"
name = "u701hybrid"

[package.metadata.esp-idf-sys]
esp_idf_version = "tag:v4.4.6"
esp_idf_tools_install_dir = "global"

[build-dependencies]
embuild = "0.31.2"
