services:
  # Main development environment
  u701-dev:
    build:
      context: .
      args:
        RUST_VERSION: 1.75.0
    container_name: u701-dev
    volumes:
      # Mount source code for live development
      - .:/home/esp32/workspace
      # Persist cargo registry and build cache
      - cargo-registry:/home/esp32/.cargo/registry
      - cargo-git:/home/esp32/.cargo/git
      - target-cache:/home/esp32/workspace/target
      - pio-cache:/home/esp32/.platformio
    environment:
      - CARGO_HOME=/home/esp32/.cargo
      - PLATFORMIO_CORE_DIR=/home/esp32/.platformio
      - ESPUP_PATH=/home/esp32/tmp/espup.sh
    devices:
      # ESP32 USB devices - adjust as needed for your system
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /home/esp32/workspace
    command: /bin/bash

  # Build-only service for CI/CD
  u701-builder:
    build:
      context: .
      args:
        RUST_VERSION: 1.75.0
    container_name: u701-builder
    volumes:
      - .:/home/esp32/workspace
      - cargo-registry:/home/esp32/.cargo/registry
      - cargo-git:/home/esp32/.cargo/git
    environment:
      - CARGO_HOME=/home/esp32/.cargo
      - ESPUP_PATH=/home/esp32/tmp/espup.sh
    working_dir: /home/esp32/workspace

  # OTA server for wireless flashing
  u701-ota:
    build:
      context: .
    container_name: u701-ota
    volumes:
      - .:/home/esp32/workspace
      - cargo-registry:/home/esp32/.cargo/registry
      - cargo-git:/home/esp32/.cargo/git
    environment:
      - CARGO_HOME=/home/esp32/.cargo
      - ESPUP_PATH=/home/esp32/tmp/espup.sh
    ports:
      - "3232:3232"
    working_dir: /home/esp32/workspace
    command: /bin/bash -c "source ${ESPUP_PATH} && just ota"

volumes:
  cargo-registry:
  cargo-git:
  target-cache:
  pio-cache:

networks:
  default:
    driver: bridge