match_block_trailing_comma = true
use_small_heuristics = "Max"
normalize_comments = false
newline_style = "Auto"
fn_call_width = 100
hard_tabs = false
max_width = 170
tab_spaces = 2

imports_indent = "Block"

struct_lit_single_line = false
struct_field_align_threshold = 20
single_line_let_else_max_width = 0
reorder_modules = false
group_imports = "One"
reorder_imports = false
reorder_impl_items = true
where_single_line = true
imports_granularity = "Module"
imports_layout = "Horizontal"
force_multiline_blocks = true
fn_params_layout = "Compressed"
trailing_comma = "Never"
use_field_init_shorthand = true
