# Enable 64 bit: --cfg espidf_time64
[build]
target = "xtensa-esp32-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]

[unstable]
# build-std = ["std", "panic_abort"]
build-std = ["core", "panic_abort", "alloc", "std"]

[profile]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = false
rpath = false


[env]

LIBCLANG_PATH = "/Users/linusoleander/.rustup/toolchains/esp/xtensa-esp32-elf-clang/esp-16.0.0-20230516/esp-clang/lib"
