# Enable 64 bit: --cfg espidf_time64
[build]
# target = "xtensa-esp32-espidf"
target = "aarch64-apple-darwin"

[target.aarch64-apple-darwin]
rustflags = ["-Z", "macro-backtrace"]

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]

[target.xtensa-esp32-espidf]
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]

[unstable]
build-std = ["core", "panic_abort", "std"]
