[build]
# target = "xtensa-esp32-espidf"
target = "riscv32imc-esp-espidf"
# target = "aarch64-apple-darwin"

# target = "thumbv7em-none-eabihf"

# [target.thumbv7em-none-eabihf]


[unstable]
build-std = ["panic_abort", "alloc", "core", "std"]

# [profile.release]
# opt-level = "z"
# lto = true

[env]
RUST_LOG = "debug"
LIBCLANG_PATH="/Users/linusoleander/.rustup/toolchains/esp/xtensa-esp32-elf-clang/esp-16.0.0-20230516/esp-clang/lib"

