[build]
target = "riscv32imc-esp-espidf"
# target = "xtensa-esp32-espidf"
# target = "aarch64-apple-darwin"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]

# [profile.release]
# opt-level = "z"
# lto = true

[env]
RUST_LOG = "debug"
ESP_IDF_VERSION = "v4.6.6"
