[build]
# target = "xtensa-esp32-espidf"
# target = "riscv32imc-esp-espidf"
target = "aarch64-apple-darwin"

[unstable]
build-std = ["std", "panic_abort", "alloc"]

[profile.release]
opt-level = "z"
lto = true

[env]
RUST_LOG = "debug"
ESP_IDF_VERSION = "v4.6.6"
