[build]
# target = "riscv32imc-esp-espidf"
target = "xtensa-esp32-espidf"
# target = "aarch64-apple-darwin"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64","-C", "default-linker-libraries"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "v5.1.1"
