[build]
# target = "riscv32imc-esp-espidf"
# target = "xtensa-esp32-espidf"
target =  "xtensa-esp32-elf"
# target = "aarch64-apple-darwin"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
# rustflags = ["--cfg", "espidf_time64","-C", "default-linker-libraries"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"

# rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[target.xtensa-esp32-elf]
linker = "ldproxy"
# rustflags = ["-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

# [env]
# ESP_IDF_VERSION = "v.4.4.4"
