[build]
target = "xtensa-esp32-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --baud 921600 --port /dev/cu.SLAB_USBtoUART --monitor"
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]#, "--cfg", "espidf_time64"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash -b 921600 -p /dev/tty.SLAB_USBtoUART --monitor"
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]

[unstable]
build-std = ["std", "panic_abort"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = false
rpath = false

[profile.dev]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = false
rpath = false
