name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.platformio
            target
            .pio
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src

      - name: Remove problematic configs for build
        run: |
          rm -f rust-toolchain.toml
          mv .cargo/config.toml .cargo/config.toml.bak

      - name: Build project (basic)
        run: cargo build --workspace

      - name: Restore config
        run: mv .cargo/config.toml.bak .cargo/config.toml

      - name: Install PlatformIO dependencies
        run: |
          cargo install cargo-binstall --force
          cargo binstall cargo-pio espup -y --force

      - name: Install PlatformIO
        run: cargo pio installpio

      - name: PlatformIO check
        run: cargo pio exec -- check