name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Temporarily remove cargo config for standard build
        run: |
          if [ -f .cargo/config.toml ]; then
            mv .cargo/config.toml .cargo/config.toml.bak
          fi

      - name: Build project
        run: cargo build --workspace

      - name: Run tests
        run: cargo test --workspace

      - name: Restore cargo config
        run: |
          if [ -f .cargo/config.toml.bak ]; then
            mv .cargo/config.toml.bak .cargo/config.toml
          fi
