name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cargo
            target
            .pio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Setup rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src
          toolchain: nightly

      - name: Remove rust-toolchain.toml
        run: rm -f rust-toolchain.toml

      - name: Install cargo-pio and espup
        run: |
          cargo +nightly install cargo-binstall --force
          cargo +nightly binstall cargo-pio espup -y --force

      - name: Install PlatformIO
        run: cargo +nightly pio installpio

      - name: Build PlatformIO check
        run: cargo +nightly pio exec -- check

      - name: Install ESP toolchain
        run: |
          if [ -f .env ]; then
            source .env
            espup install -t ${MCU:-esp32c3} -f .espup.sh
          else
            espup install -t esp32c3 -f .espup.sh
          fi

      - name: Build using PlatformIO
        run: |
          source .espup.sh
          cargo +esp pio build || cargo +nightly pio build
