name: PlatformIO CI
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cargo
            target
            .pio
            ~/.espressif
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
            ${{ runner.os }}-pio-

      - name: Setup rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Install espup and setup ESP toolchain
        run: |
          # Install espup first without using custom toolchain
          RUSTUP_TOOLCHAIN=nightly cargo install espup --version 0.14.0 --locked
          espup install -t esp32 -f .espup.sh
          # Source the ESP environment setup file
          source .espup.sh
          # Create a symbolic link for the 'esp' toolchain if needed
          if [ ! -d ~/.rustup/toolchains/esp ]; then
            rustup toolchain link esp ~/.rustup/toolchains/esp
          fi

      - name: Install cargo tools
        run: |
          source .espup.sh
          cargo install cargo-binstall
          cargo binstall cargo-pio -y

      - name: Install PlatformIO
        run: |
          source .espup.sh
          cargo pio installpio

      - name: Build PlatformIO check
        run: |
          source .espup.sh
          cargo pio exec -- check

      - name: Build using PlatformIO
        run: |
          source .espup.sh
          cargo +esp pio build
