name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio
            ~/.cargo
            target
            .pio
          key: ${{ hashFiles('platformio.ini') }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup rust nightly
        uses: actions-rs/toolchain@v1
        with:
          components: rust-src,rust-std
          toolchain: nightly
          override: true

      - name: Remove rust-toolchain.toml
        run: rm rust-toolchain.toml

      - name: Install cargo-pio and espup
        run: |
          cargo +nightly install cargo-binstall
          cargo +nightly binstall cargo-pio espup -y

      - name: Install PlatformIO
        run: cargo +nightly pio installpio

      - name: Build PlatformIO examples
        run: cargo +nightly pio exec -- check

      - name: Build using PlatformIO
        run: |
          source .env
          espup install -t $MCU -f .espup.sh
          source .espup.sh
          cargo +esp pio build
