name: PlatformIO CI
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cargo
            target
            .pio
          key: ${{ hashFiles('platformio.ini') }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Install cargo-pio and espup
        run: |
          cargo install cargo-binstall
          cargo binstall cargo-pio espup -y

      - name: Install PlatformIO
        run: cargo pio installpio

      - name: Build PlatformIO check
        run: cargo pio exec -- check

      - name: Build using PlatformIO
        run: |
          espup install -t esp32 -f .espup.sh
          source .espup.sh
          cargo +esp pio build
