name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Cache PlatformIO dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.pio
      #     key: ${{ hashFiles('platformio.ini') }}

      - name: Setup rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install cargo-pio
        run: cargo +nightly install cargo-pio

      - name: Install PlatformIO
        run: cargo +nightly pio installpio

      - name: Build PlatformIO examples
        run: cargo +nightly pio exec -- check
