name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio
            ~/.cargo
            target
            .pio
          key: ${{ hashFiles('platformio.ini') }}

      - name: Setup rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src,rust-std
      - run: rm rust-toolchain.toml

      - name: Install cargo-pio
        run: cargo +nightly install cargo-pio

      - name: Install PlatformIO
        run: cargo +nightly pio installpio

      - name: Build PlatformIO examples
        run: cargo +nightly pio exec -- check

      - name: Install espup
        run: cargo +nightly install espup

      - name: Build
        run: |
          source .env
          espup install -t $MCU -f .espup.sh
          source .espup.sh
          cargo +esp pio build
