name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, rustfmt, clippy

      - name: Install espup and ESP toolchain
        run: |
          cargo install cargo-binstall
          cargo binstall espup -y
          espup install -t esp32 -f .espup.sh

      - name: Run tests (main)
        run: cargo test --verbose --target x86_64-unknown-linux-gnu

      - name: Build (main)
        run: |
          source .espup.sh
          cargo build --target xtensa-esp32-espidf

      - name: Run tests (machine)
        run: cargo test --verbose --package machine --target x86_64-unknown-linux-gnu

      - name: Clippy (main)
        run: |
          source .espup.sh
          cargo clippy --workspace --all-targets --all-features -- -D warnings

      # - name: Clippy (machine)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: --workspace --all-targets --all-features -- -D warnings --target x86_64-unknown-linux-gnu

      # - name: fmt (main)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: -- --check

      # - name: fmt (machine)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: -- --check --target x86_64-unknown-linux-gnu
