name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: rm rust-toolchain.toml

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src, rustfmt, clippy

      - name: Run tests (main)
        run: cargo test --verbose --target x86_64-unknown-linux-gnu

      - name: Run tests (machine)
        run: cargo test --verbose --package machine --target x86_64-unknown-linux-gnu

      - name: Clippy (main)
        run: cargo clippy --workspace --all-targets --target x86_64-unknown-linux-gnu -- -D warnings

      # - name: Clippy (machine)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: --workspace --all-targets --all-features -- -D warnings --target x86_64-unknown-linux-gnu

      # - name: fmt (main)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: -- --check

      # - name: fmt (machine)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: -- --check --target x86_64-unknown-linux-gnu
