name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Modify the toolchain for CI compatibility
      - name: Setup CI toolchain file
        run: |
          mv rust-toolchain.toml rust-toolchain.original.toml
          cat > rust-toolchain.toml << 'EOF'
          [toolchain]
          channel = "nightly"
          components = ["rust-src"]
          EOF

      - name: Cache Cargo and ESP dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cargo
            ~/.rustup
            ~/.espressif
            target
            .pio
            .espup.sh
          key: ${{ runner.os }}-cargo-esp-${{ hashFiles('**/Cargo.lock', '**/platformio.ini') }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-esp-${{ hashFiles('**/Cargo.lock', '**/platformio.ini') }}
            ${{ runner.os }}-cargo-esp-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, rustfmt, clippy

      - name: Install espup and ESP toolchain
        run: |
          # Check if we already have espup from cache
          if ! command -v espup &> /dev/null; then
            echo "Installing espup from scratch..."
            # Install espup first without using custom toolchain
            RUSTUP_TOOLCHAIN=nightly cargo install espup --version 0.14.0 --locked
          else
            echo "Using cached espup installation"
          fi

          # Check if ESP toolchain is already installed from cache
          if [ ! -f .espup.sh ] || [ ! -d ~/.rustup/toolchains/esp ]; then
            echo "Installing ESP toolchain from scratch..."
            # Install Xtensa toolchain for ESP32
            espup install -t esp32 -f .espup.sh
          else
            echo "Using cached ESP toolchain"
          fi

          # Source the ESP environment setup file
          source .espup.sh
          
          # Create a symbolic link for the 'esp' toolchain if needed
          if [ ! -d ~/.rustup/toolchains/esp ]; then
            rustup toolchain link esp ~/.rustup/toolchains/esp
          fi
          
          # Check if cargo-pio is already installed
          if ! command -v cargo-pio &> /dev/null; then
            echo "Installing cargo-pio..."
            # Install cargo-pio and other required tools
            cargo install cargo-pio
          else
            echo "Using cached cargo-pio installation"
          fi
          
          # Debug ESP toolchain setup
          echo "Listing Rust toolchains:"
          rustup toolchain list
          echo "Checking ESP toolchain:"
          ls -la ~/.rustup/toolchains/esp/bin/ || echo "ESP toolchain bin directory not found"
          
          # Add target explicitly to avoid ${CARGO_BUILD_TARGET} issue
          echo "Adding xtensa target to ESP toolchain"
          rustup target add --toolchain esp xtensa-esp32-espidf || echo "Target may already be installed"

      - name: Run tests (main)
        run: cargo test --verbose --target x86_64-unknown-linux-gnu

      - name: Build (main)
        run: |
          source .espup.sh
          RUSTUP_TOOLCHAIN=esp cargo build --target xtensa-esp32-espidf

      - name: Run tests (machine)
        run: cargo test --verbose --package machine --target x86_64-unknown-linux-gnu

      - name: Clippy (main)
        run: |
          source .espup.sh
          RUSTUP_TOOLCHAIN=esp cargo clippy --workspace --all-targets --all-features -- -D warnings

      # - name: Clippy (machine)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: --workspace --all-targets --all-features -- -D warnings --target x86_64-unknown-linux-gnu

      # - name: fmt (main)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: -- --check

      # - name: fmt (machine)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: -- --check --target x86_64-unknown-linux-gnu
