name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_HOME: /home/runner/.cargo
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ~/.rustup
            ~/.espressif
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, clippy

      - name: Run tests (machine)
        run: cargo test --verbose --package machine --target x86_64-unknown-linux-gnu

      - name: Setup ESP toolchain
        run: |
          # Install espup and ESP toolchain
          if ! command -v espup &> /dev/null; then
            RUSTUP_TOOLCHAIN=nightly cargo install espup --version 0.14.0 --locked
          fi

          espup install -t esp32 -f .espup.sh
          source .espup.sh

          if [ ! -d ~/.rustup/toolchains/esp ]; then
            rustup toolchain link esp ~/.rustup/toolchains/esp
          fi

          rustup target add --toolchain esp xtensa-esp32-espidf || true

      - name: Clippy
        run: |
          source .espup.sh
          RUSTUP_TOOLCHAIN=esp cargo clippy --target xtensa-esp32-espidf -- -D warnings