name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ hashFiles('**/Cargo.lock') }}

      - run: # rm rust-toolchain.toml

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, rustfmt, clippy

      - name: Run tests (main)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose  --target x86_64-unknown-linux-gnu

      - name: Build (main)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target riscv32imc-esp-espidf

      - name: Run tests (machine)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --workspace machine --target x86_64-unknown-linux-gnu

      - name: Clippy (main)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          toolchain: esp
          args: --workspace --all-targets --all-features -- -D warnings

      # - name: Clippy (machine)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: --workspace --all-targets --all-features -- -D warnings --target x86_64-unknown-linux-gnu

      # - name: fmt (main)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: -- --check

      # - name: fmt (machine)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: -- --check --target x86_64-unknown-linux-gnu
